//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_te6woUg9EeKGbNSAHWDTsQ,_xlEGoUg9EeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/interacao_1_FBD842A0_66a5b85d_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_mqXowEg_EeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/construcao_373B2F13_97411b40_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,__iDO0EhREeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/transicao_762A18C6_d63004f3_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_te6woUg9EeKGbNSAHWDTsQ,_Ym8_cUr_EeKX7P2uP3m2zgActivity"]="./../../openup/deliveryprocesses/resources/Iteração 2_7DDE3357_e8aba914_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/sigar_ciclo_vida_C39818D9_c39818d9_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_mqXowEg_EeKGbNSAHWDTsQ,_Xx_TsUhJEeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/Iteracao4_A5CEA1EB_3e868b7f_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_mqXowEg_EeKGbNSAHWDTsQ,_Xx_TsUhJEeKGbNSAHWDTsQ,_TowYAkhKEeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/develop_solution_B9CD6BDC_645db8af_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_JeztgEg_EeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/elaboracao_BA7B68BD_1a8154ea_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_te6woUg9EeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/iniciacao_8709663C_e70f5269_Activity.jpeg"
contentPage.processPage.imageFiles["_m-9DkUg9EeKGbNSAHWDTsQ,_JeztgEg_EeKGbNSAHWDTsQ,_Wzf54UhDEeKGbNSAHWDTsQActivity"]="./../../openup/deliveryprocesses/resources/iteracao_1_2B3AB561_106afa9f_Activity.jpeg"
contentPage.processPage.imageFiles["_0sx7islgEdmt3adZL5Dmdw,_bWELsd1qEduavbdP4P0fvwActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_436ECE62_92eadf8b_Activity.jpeg"
contentPage.processPage.imageFiles["_0sx7islgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/develop_architecture_AF0A71D5_af0a71d5_Activity.jpeg"
contentPage.processPage.imageFiles["_h2-iAfimEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_633E2E80_633e2e80_Activity.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5Dmdw,_0okw8clgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_797D013F_22de28d9_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5Dmdw,_0oreoclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/agree_technical_approach_944692EF_3da7ba89_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/inception_phase_iteration_C2188B46_c2188b46_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_xupMvxOKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/inception_phase_iteration_648AE2DA_4ce4ab08_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_467NIhOKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/transition_phase_iteration_31BFECF6_1a19b524_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/elaboration_phase_iteration_427C4DE0_2ad6160e_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/construction_phase_iteration_A276D580_8ad09dae_Activity.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/elaboration_phase_iteration_97E7400D_97e7400d_Activity.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_WrXvwPinEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_D6782BA8_357e309_Activity.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_WrXvwPinEdmugcVr9AdHjQActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_D6782BA8_357e309_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRgActivity"]="./../../openup/capabilitypatterns/resources/construction_phase_iteration_FB82CA56_fb82ca56_Activity.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRg,_nen3UexwEduRmOwej6GrogActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_4DCE9885_3891cf2f_Activity.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5Dmdw,_0DMlYPinEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_EE81900_51153c26_Activity.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/transition_phase_iteration_87676AD2_87676ad2_Activity.jpeg"
contentPage.processPage.elementUrls["_ZIYhIDlJEdyTZ9G7ByfQTw"] = ["Plano de Iteração","openup/capabilitypatterns/iteration_plan_309C6824.html"];
contentPage.processPage.elementUrls["_mqXowEg_EeKGbNSAHWDTsQ"] = ["Construção","openup/deliveryprocesses/construcao_373B2F13.html"];
contentPage.processPage.elementUrls["_0sx7islgEdmt3adZL5Dmdw"] = ["Desenvolver a Arquitetura","openup/capabilitypatterns/develop_architecture_AF0A71D5.html"];
contentPage.processPage.elementUrls["_S8dNQsBFEdqSgKaj2SZBmg"] = ["Testador","openup/capabilitypatterns/tester_433F66E5.html"];
contentPage.processPage.elementUrls["_ny2fQL3SEdqfrv3k16plXw"] = ["Construção","openup/capabilitypatterns/build_BA125429.html"];
contentPage.processPage.elementUrls["_Xr0twgSqEdy6Meh4O3uDnA"] = ["Especificação de Requisitos Suplementares","openup/capabilitypatterns/supporting_requirements_spec_2EAAB5B1.html"];
contentPage.processPage.elementUrls["_6QwpgQ1SEdyKD8XBf_Hbrw"] = ["Implementação","openup/capabilitypatterns/implementation_23DE2C46.html"];
contentPage.processPage.elementUrls["_3FYGMEr-EeKX7P2uP3m2zg"] = ["Criar Cronograma","openup/deliveryprocesses/Criar Cronograma_B29881D1.html"];
contentPage.processPage.elementUrls["_BmbHQU_cEduE1dJ2XtzzkQ"] = ["Testador","openup/capabilitypatterns/tester_DED65E84.html"];
contentPage.processPage.elementUrls["_KAnAYE9PEdumneEH4I4Yqg"] = ["Analista","openup/capabilitypatterns/analyst_F0254DCC.html"];
contentPage.processPage.elementUrls["_1Pm3YEr-EeKX7P2uP3m2zg"] = ["Planejar Comunicação Externa","openup/deliveryprocesses/comunicao_externa_61B25969.html"];
contentPage.processPage.elementUrls["_oR39mb3SEdqfrv3k16plXw"] = ["Executar os Testes","openup/capabilitypatterns/run_tests_84871F0D.html"];
contentPage.processPage.elementUrls["_0rWYIslgEdmt3adZL5Dmdw"] = ["Planejar e Gerenciar a iteração","openup/capabilitypatterns/manage_iteration_84F991D7.html"];
contentPage.processPage.elementUrls["_piI90DlJEdyTZ9G7ByfQTw"] = ["Plano de Iteração","openup/capabilitypatterns/iteration_plan_E494B488.html"];
contentPage.processPage.elementUrls["_d5-nQFY4EdqI9sTOt2pjHw"] = ["Arquiteto","openup/capabilitypatterns/architect_CB606A14.html"];
contentPage.processPage.elementUrls["_PJJ3A0_dEduE1dJ2XtzzkQ"] = ["Gerente de Projeto","openup/capabilitypatterns/project_manager_53471702.html"];
contentPage.processPage.elementUrls["_cHgcEUhBEeKGbNSAHWDTsQ"] = ["Configurar Ambiente","openup/deliveryprocesses/configurar_ambiente_39D8183D.html"];
contentPage.processPage.elementUrls["_VpJUskhFEeKGbNSAHWDTsQ"] = ["Refinar os Requisitos","openup/deliveryprocesses/identify_and_refine_requirements_888AB7AD.html"];
contentPage.processPage.elementUrls["__1T74ClZEdytYo99TZh2Ng"] = ["Desenvolvedor","openup/capabilitypatterns/developer_B36C868A.html"];
contentPage.processPage.elementUrls["_uknUwb-EEdqb7N6KIeDL8Q"] = ["Design","openup/capabilitypatterns/design_3CF17018.html"];
contentPage.processPage.elementUrls["_Wzf54UhDEeKGbNSAHWDTsQ"] = ["Iteração 3","openup/deliveryprocesses/iteracao_1_2B3AB561.html"];
contentPage.processPage.elementUrls["_6Qwpgg1SEdyKD8XBf_Hbrw"] = ["Teste de Desenvolvedor","openup/capabilitypatterns/developer_test_1277405C.html"];
contentPage.processPage.elementUrls["_DUCuoDk-EduFTqg5hiiQIw"] = ["Lista de Riscos","openup/capabilitypatterns/risk_list_248B8AAB.html"];
contentPage.processPage.elementUrls["_uknUwL-EEdqb7N6KIeDL8Q"] = ["Especificação de Requisitos Suplementares","openup/capabilitypatterns/supporting_requirements_spec_4E585C02.html"];
contentPage.processPage.elementUrls["_0sTaYMlgEdmt3adZL5Dmdw"] = ["Iteração da Fase de Elaboração","openup/capabilitypatterns/elaboration_phase_iteration_97E7400D.html"];
contentPage.processPage.elementUrls["_kF8tYTbsEduMn613sF6-Uw"] = ["Caso de Teste","openup/capabilitypatterns/test_case_61ADF20F.html"];
contentPage.processPage.elementUrls["_h2-iAfimEdmugcVr9AdHjQ"] = ["Desenvolver um Incremento da Solução","openup/capabilitypatterns/develop_solution_633E2E80.html"];
contentPage.processPage.elementUrls["_a_F1YFY2EdqI9sTOt2pjHw"] = ["Script de Teste","openup/capabilitypatterns/test_script_56F46221.html"];
contentPage.processPage.elementUrls["_eFeO00bpEduLBN1xMBngqw"] = ["Modelo de Caso de Uso","openup/capabilitypatterns/uc_model_AD897B15.html"];
contentPage.processPage.elementUrls["_BmbHQE_cEduE1dJ2XtzzkQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_D4387E74.html"];
contentPage.processPage.elementUrls["_0DMlYPinEdmugcVr9AdHjQ"] = ["Desenvolver um Incremento da Solução","openup/capabilitypatterns/develop_solution_EE81900.html"];
contentPage.processPage.elementUrls["_y_PjTOtQEdqc1LGhiSPqRg"] = ["Executar Tarefas Contínuas","openup/capabilitypatterns/ongoing_tasks_2F5F2C64.html"];
contentPage.processPage.elementUrls["_eE5nEUbpEduLBN1xMBngqw"] = ["Identificar e Refinar os Requisitos","openup/capabilitypatterns/identify_and_refine_requirements_E2BECCD3.html"];
contentPage.processPage.elementUrls["_te6woUg9EeKGbNSAHWDTsQ"] = ["Iniciação","openup/deliveryprocesses/iniciacao_8709663C.html"];
contentPage.processPage.elementUrls["_SZOIoUmSEduO0bs89Khm8Q"] = ["Visão","openup/capabilitypatterns/vision_99C2DC0C.html"];
contentPage.processPage.elementUrls["_ViHqkEsBEeKX7P2uP3m2zg"] = ["Visão","openup/deliveryprocesses/vision_75A97862.html"];
contentPage.processPage.elementUrls["_0qxwYclgEdmt3adZL5Dmdw"] = ["Executar Tarefas Contínuas","openup/capabilitypatterns/ongoing_tasks_ACB4F513.html"];
contentPage.processPage.elementUrls["_eG0SoEbpEduLBN1xMBngqw"] = ["Glossário","openup/capabilitypatterns/glossary_FA2071A5.html"];
contentPage.processPage.elementUrls["_PJJ3AU_dEduE1dJ2XtzzkQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_FBD42D27.html"];
contentPage.processPage.elementUrls["_v0mnQUr-EeKX7P2uP3m2zg"] = ["Desenvolver Visão Técnica","openup/deliveryprocesses/Desenvolver Visão Técnica_5CF24CB7.html"];
contentPage.processPage.elementUrls["_2tHGoMAYEdqX-s4mWhkyqQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_1B0F1D9A.html"];
contentPage.processPage.elementUrls["_DT8oADk-EduFTqg5hiiQIw"] = ["Analista","openup/capabilitypatterns/analyst_FFC972FD.html"];
contentPage.processPage.elementUrls["_SZICAEmSEduO0bs89Khm8Q"] = ["Planejar a Iteração","openup/capabilitypatterns/plan_iteration_FD2509AA.html"];
contentPage.processPage.elementUrls["_TAVx0CliEdqjQsaFX0CJTw"] = ["Executar Tarefas Contínuas","openup/capabilitypatterns/ongoing_tasks_7DF42BFF.html"];
contentPage.processPage.elementUrls["_a6qBUFY2EdqI9sTOt2pjHw"] = ["Testador","openup/capabilitypatterns/tester_D0AD07C2.html"];
contentPage.processPage.elementUrls["_JeztgEg_EeKGbNSAHWDTsQ"] = ["Elaboração","openup/deliveryprocesses/elaboracao_BA7B68BD.html"];
contentPage.processPage.elementUrls["_RfIyYkhFEeKGbNSAHWDTsQ"] = ["Planejar e Gerenciar a iteração","openup/deliveryprocesses/manage_iteration_FDFD27C6.html"];
contentPage.processPage.elementUrls["_ntNoEA1NEdyKD8XBf_Hbrw"] = ["Integrar e Criar a Construção","openup/capabilitypatterns/integrate_and_create_build_7C2BDD46.html"];
contentPage.processPage.elementUrls["_cL1KIL-FEdqb7N6KIeDL8Q"] = ["Projetar a Solução","openup/capabilitypatterns/design_solution_1FD864B7.html"];
contentPage.processPage.elementUrls["_y-3IretQEdqc1LGhiSPqRg"] = ["Testar a Solução","openup/capabilitypatterns/test_solution_F0E4EA46.html"];
contentPage.processPage.elementUrls["_d4k_0L-FEdqb7N6KIeDL8Q"] = ["Registro de Teste","openup/capabilitypatterns/test_log_D1C23AD1.html"];
contentPage.processPage.elementUrls["_DT8oAjk-EduFTqg5hiiQIw"] = ["Testador","openup/capabilitypatterns/tester_F9006723.html"];
contentPage.processPage.elementUrls["_Y42y8L-EEdqb7N6KIeDL8Q"] = ["Encontrar e Descrever os Requisitos","openup/capabilitypatterns/find_and_outline_requirements_24FC0F26.html"];
contentPage.processPage.elementUrls["_zRLfAUsCEeKX7P2uP3m2zg"] = ["Iteração 5","openup/deliveryprocesses/Iteracao 5_2B78FF93.html"];
contentPage.processPage.elementUrls["_86w-oOB4EdqnKu908IEluw"] = ["Glossário","openup/capabilitypatterns/glossary_2966685C.html"];
contentPage.processPage.elementUrls["_lqOzsL-EEdqb7N6KIeDL8Q"] = ["Descrever a Arquitetura","openup/capabilitypatterns/outline_the_architecture_79FA3059.html"];
contentPage.processPage.elementUrls["_yaTzUEsAEeKX7P2uP3m2zg"] = ["Lista de Itens de Trabalho","openup/deliveryprocesses/work_items_list_4D58F369.html"];
contentPage.processPage.elementUrls["_m-9DkUg9EeKGbNSAHWDTsQ"] = ["Ciclo de Vida do Sigar","openup/deliveryprocesses/sigar_ciclo_vida_C39818D9.html"];
contentPage.processPage.elementUrls["_nykLZL3SEdqfrv3k16plXw"] = ["Implementar os Scripts de Teste","openup/capabilitypatterns/implement_test_scripts_52EE14CD.html"];
contentPage.processPage.elementUrls["_Xr0twQSqEdy6Meh4O3uDnA"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_4011A19B.html"];
contentPage.processPage.elementUrls["_ZRfVYL-EEdqb7N6KIeDL8Q"] = ["Detalhar os Requisitos","openup/capabilitypatterns/detail_requirements_6AD0E2CB.html"];
contentPage.processPage.elementUrls["_yhY9oEr-EeKX7P2uP3m2zg"] = ["Planejar Comunicação Interna","openup/deliveryprocesses/comunicacao_interna_388D3FD.html"];
contentPage.processPage.elementUrls["_oNnk0FY5EdqI9sTOt2pjHw"] = ["Lista de Itens de Trabalho","openup/capabilitypatterns/work_items_list_3834F5A0.html"];
contentPage.processPage.elementUrls["_ezOKIU9DEdudU75l2xOQTw"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_25128EF9.html"];
contentPage.processPage.elementUrls["_0ruyoclgEdmt3adZL5Dmdw"] = ["Identificar e Refinar os Requisitos","openup/capabilitypatterns/identify_and_refine_requirements_824699A3.html"];
contentPage.processPage.elementUrls["_vxwcsEsAEeKX7P2uP3m2zg"] = ["Gerente de Projeto","openup/deliveryprocesses/project_manager_156FD86B.html"];
contentPage.processPage.elementUrls["_gWEDYUsDEeKX7P2uP3m2zg"] = ["Lista de Riscos","openup/deliveryprocesses/risk_list_9003B639.html"];
contentPage.processPage.elementUrls["_TowYAkhKEeKGbNSAHWDTsQ"] = ["Desenvolver um Incremento da Solução","openup/deliveryprocesses/develop_solution_B9CD6BDC.html"];
contentPage.processPage.elementUrls["_16nd0BOKEduCNqgZdt_OaA"] = ["Marco da Arquitetura no Ciclo de Vida","openup/deliveryprocesses/lifecycle_architecture_E32228EB.html"];
contentPage.processPage.elementUrls["_31E_YBOKEduCNqgZdt_OaA"] = ["Marco da Capacidade Operacional Inicial","openup/deliveryprocesses/initial_operational_capability_F4ECB9F.html"];
contentPage.processPage.elementUrls["_79bQ4DoCEdu0yYZ2bsCXog"] = ["Definir a Visão","openup/capabilitypatterns/define_vision_AED53484.html"];
contentPage.processPage.elementUrls["_9k_AcFY4EdqI9sTOt2pjHw"] = ["Design","openup/capabilitypatterns/design_C4187064.html"];
contentPage.processPage.elementUrls["_cMHeAL-FEdqb7N6KIeDL8Q"] = ["Especificação de Requisitos Suplementares","openup/capabilitypatterns/supporting_requirements_spec_BABA7963.html"];
contentPage.processPage.elementUrls["_XKDWIFY5EdqI9sTOt2pjHw"] = ["Planejar o Projeto","openup/capabilitypatterns/plan_the_project_1CC89731.html"];
contentPage.processPage.elementUrls["_cnzUcL-FEdqb7N6KIeDL8Q"] = ["Implementar os Testes de Desenvolvedor","openup/capabilitypatterns/impl_developer_tests_D8C7E9A0.html"];
contentPage.processPage.elementUrls["_cMHeAb-FEdqb7N6KIeDL8Q"] = ["Caderno de Arquitetura","openup/capabilitypatterns/architecture_notebook_A9538D79.html"];
contentPage.processPage.elementUrls["_d4GesL-FEdqb7N6KIeDL8Q"] = ["Executar os Testes de Desenvolvedor","openup/capabilitypatterns/run_developer_tests_832C8E18.html"];
contentPage.processPage.elementUrls["_0sluQslgEdmt3adZL5Dmdw"] = ["Obter Acordo Sobre a Abordagem Técnica","openup/capabilitypatterns/agree_technical_approach_350ADF37.html"];
contentPage.processPage.elementUrls["_r1QxIDeqEduCsbgJNeFsSw"] = ["Gerente de Projeto","openup/capabilitypatterns/project_manager_56901073.html"];
contentPage.processPage.elementUrls["_eGoFYkbpEduLBN1xMBngqw"] = ["Encontrar e Descrever os Requisitos","openup/capabilitypatterns/find_and_outline_requirements_9DFAC1B5.html"];
contentPage.processPage.elementUrls["_A7yxsEr_EeKX7P2uP3m2zg"] = ["Criar EAP","openup/deliveryprocesses/Criar EAP_5D4C2711.html"];
contentPage.processPage.elementUrls["_VZk0YxeDEduXJrZWmtC8tg"] = ["Glossário","openup/capabilitypatterns/glossary_2D4068DC.html"];
contentPage.processPage.elementUrls["_eFeO0UbpEduLBN1xMBngqw"] = ["Caso de Uso","openup/capabilitypatterns/use_case_5616913A.html"];
contentPage.processPage.elementUrls["_vAmGIL-EEdqb7N6KIeDL8Q"] = ["Refinar a Arquitetura","openup/capabilitypatterns/refine_the_architecture_4A9BFEF8.html"];
contentPage.processPage.elementUrls["_eHAf4UbpEduLBN1xMBngqw"] = ["Testador","openup/capabilitypatterns/tester_691CA7B3.html"];
contentPage.processPage.elementUrls["_m_gdUMWrEduoutjwLchi0g"] = ["Construção","openup/capabilitypatterns/build_4E0FC635.html"];
contentPage.processPage.elementUrls["_aVdK4APYEdyB4pp30pbnFA"] = ["Lista de Itens de Trabalho","openup/capabilitypatterns/work_items_list_7F9A369F.html"];
contentPage.processPage.elementUrls["_XQQDIUhKEeKGbNSAHWDTsQ"] = ["Testar a Solucao","openup/deliveryprocesses/Testar a Solucao_4EEDB72D.html"];
contentPage.processPage.elementUrls["_3CqrAROKEduCNqgZdt_OaA"] = ["Iteração de Construção [1..n]","openup/deliveryprocesses/construction_phase_iteration_A276D580.html"];
contentPage.processPage.elementUrls["_0q33AclgEdmt3adZL5Dmdw"] = ["Planejar e Gerenciar a iteração","openup/capabilitypatterns/manage_iteration_2F27034C.html"];
contentPage.processPage.elementUrls["_eFeO0EbpEduLBN1xMBngqw"] = ["Analista","openup/capabilitypatterns/analyst_4B78B12A.html"];
contentPage.processPage.elementUrls["_mKmV0L-EEdqb7N6KIeDL8Q"] = ["Visão","openup/capabilitypatterns/vision_E89EABB3.html"];
contentPage.processPage.elementUrls["_VZk0ZBeDEduXJrZWmtC8tg"] = ["Visão","openup/capabilitypatterns/vision_EDFD76C5.html"];
contentPage.processPage.elementUrls["_jLaKwP77Edm1zMZYtD3GjA"] = ["Planejar e Gerenciar a iteração","openup/capabilitypatterns/manage_iteration_E0BEBBF4.html"];
contentPage.processPage.elementUrls["_0qrpwslgEdmt3adZL5Dmdw"] = ["Testar a Solução","openup/capabilitypatterns/test_solution_B2F7A244.html"];
contentPage.processPage.elementUrls["_0pJ_xslgEdmt3adZL5Dmdw"] = ["Executar Tarefas Contínuas","openup/capabilitypatterns/ongoing_tasks_91569239.html"];
contentPage.processPage.elementUrls["_Xx_TsUhJEeKGbNSAHWDTsQ"] = ["Iteracao 4","openup/deliveryprocesses/Iteracao4_A5CEA1EB.html"];
contentPage.processPage.elementUrls["_-Y3UcFY4EdqI9sTOt2pjHw"] = ["Teste de Desenvolvedor","openup/capabilitypatterns/developer_test_D491389E.html"];
contentPage.processPage.elementUrls["_hhnXEDeqEduCsbgJNeFsSw"] = ["Lista de Riscos","openup/capabilitypatterns/risk_list_3FF50D1B.html"];
contentPage.processPage.elementUrls["_dAoEIL-FEdqb7N6KIeDL8Q"] = ["Implementar a Solução","openup/capabilitypatterns/implement_solution_62FF3347.html"];
contentPage.processPage.elementUrls["_I2GD4EsBEeKX7P2uP3m2zg"] = ["Qualquer Papel","openup/deliveryprocesses/any_role_A215A5A3.html"];
contentPage.processPage.elementUrls["_lqbA8L-EEdqb7N6KIeDL8Q"] = ["Especificação de Requisitos Suplementares","openup/capabilitypatterns/supporting_requirements_spec_926E3848.html"];
contentPage.processPage.elementUrls["_Xr0twASqEdy6Meh4O3uDnA"] = ["Analista","openup/capabilitypatterns/analyst_3573C18B.html"];
contentPage.processPage.elementUrls["_mZVjwFY5EdqI9sTOt2pjHw"] = ["Plano de Iteração","openup/capabilitypatterns/iteration_plan_C1F43E5E.html"];
contentPage.processPage.elementUrls["_NXkrwcWpEduoutjwLchi0g"] = ["Caso de Uso","openup/capabilitypatterns/use_case_DFCA7029.html"];
contentPage.processPage.elementUrls["_Ym8_cUr_EeKX7P2uP3m2zg"] = ["Iteração 2","openup/deliveryprocesses/Iteração 2_7DDE3357.html"];
contentPage.processPage.elementUrls["_zEy3MEhBEeKGbNSAHWDTsQ"] = ["Documento de visão","openup/deliveryprocesses/documento_visao_FD70EB69.html"];
contentPage.processPage.elementUrls["_rQ9xIMjkEdqIm8AJUZUQYg"] = ["Arquiteto","openup/capabilitypatterns/architect_46C39EFC.html"];
contentPage.processPage.elementUrls["_FNQcoOhOEdu1i42xOtqziw"] = ["Desenvolvedor","openup/capabilitypatterns/developer_7B90AE28.html"];
contentPage.processPage.elementUrls["_DT8oBTk-EduFTqg5hiiQIw"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_CEF9352C.html"];
contentPage.processPage.elementUrls["_0nJNkslgEdmt3adZL5Dmdw"] = ["Planejar e Gerenciar a iteração","openup/capabilitypatterns/plan_manage_iteration_D46BADD3.html"];
contentPage.processPage.elementUrls["_J8-00MAZEdqX-s4mWhkyqQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_D553728A.html"];
contentPage.processPage.elementUrls["_eGuMBUbpEduLBN1xMBngqw"] = ["Detalhar os Requisitos","openup/capabilitypatterns/detail_requirements_13BA0F57.html"];
contentPage.processPage.elementUrls["_PJJ3AE_dEduE1dJ2XtzzkQ"] = ["Analista","openup/capabilitypatterns/analyst_F1364D17.html"];
contentPage.processPage.elementUrls["_FDFE4khGEeKGbNSAHWDTsQ"] = ["Testar a Arquitetura","openup/deliveryprocesses/testar_solucao_76AC2AA5.html"];
contentPage.processPage.elementUrls["_0okw8clgEdmt3adZL5Dmdw"] = ["Identificar e Refinar os Requisitos","openup/capabilitypatterns/identify_and_refine_requirements_797D013F.html"];
contentPage.processPage.elementUrls["_kF8tYDbsEduMn613sF6-Uw"] = ["Testador","openup/capabilitypatterns/tester_571011FF.html"];
contentPage.processPage.elementUrls["_467NIhOKEduCNqgZdt_OaA"] = ["Iteração de Transição [1..n]","openup/deliveryprocesses/transition_phase_iteration_31BFECF6.html"];
contentPage.processPage.elementUrls["_SxYoUEsBEeKX7P2uP3m2zg"] = ["Plano de Iteração","openup/deliveryprocesses/iteration_plan_80EFB537.html"];
contentPage.processPage.elementUrls["_DT8oATk-EduFTqg5hiiQIw"] = ["Arquiteto","openup/capabilitypatterns/architect_A67530D.html"];
contentPage.processPage.elementUrls["_nen3UexwEduRmOwej6Grog"] = ["Desenvolver um Incremento da Solução","openup/capabilitypatterns/develop_solution_4DCE9885.html"];
contentPage.processPage.elementUrls["_PFnTkOB7EdqnKu908IEluw"] = ["Glossário","openup/capabilitypatterns/glossary_BB0E50AB.html"];
contentPage.processPage.elementUrls["_os33gL3SEdqfrv3k16plXw"] = ["Lista de Itens de Trabalho","openup/capabilitypatterns/work_items_list_C83C1958.html"];
contentPage.processPage.elementUrls["_y-3IrutQEdqc1LGhiSPqRg"] = ["Iteração da Fase de Construção","openup/capabilitypatterns/construction_phase_iteration_FB82CA56.html"];
contentPage.processPage.elementUrls["_Y5DAML-EEdqb7N6KIeDL8Q"] = ["Lista de Itens de Trabalho","openup/capabilitypatterns/work_items_list_9DA841A8.html"];
contentPage.processPage.elementUrls["_9JHQUCNDEdy8morYWHvpBw"] = ["Desenvolvedor","openup/capabilitypatterns/developer_1F4B3044.html"];
contentPage.processPage.elementUrls["_F6WiEcEQEduTGJ8i4u8TMw"] = ["Desenvolvedor","openup/capabilitypatterns/developer_462E0524.html"];
contentPage.processPage.elementUrls["_VNvacFY5EdqI9sTOt2pjHw"] = ["Visão","openup/capabilitypatterns/vision_729CA9B4.html"];
contentPage.processPage.elementUrls["_32qLEUg-EeKGbNSAHWDTsQ"] = ["Visao do Projeto","openup/deliveryprocesses/Visao do Projeto_3D120382.html"];
contentPage.processPage.elementUrls["_DT8oBDk-EduFTqg5hiiQIw"] = ["Qualquer Papel","openup/capabilitypatterns/any_role_C45B551C.html"];
contentPage.processPage.elementUrls["_0pWNA8lgEdmt3adZL5Dmdw"] = ["Iniciar o Projeto","openup/capabilitypatterns/initiate_project_D9C03857.html"];
contentPage.processPage.elementUrls["_ezOKIk9DEdudU75l2xOQTw"] = ["Caso de Uso","openup/capabilitypatterns/use_case_13ABA30F.html"];
contentPage.processPage.elementUrls["_wG28gFY6EdqI9sTOt2pjHw"] = ["Modelo de Caso de Uso","openup/capabilitypatterns/uc_model_66875B44.html"];
contentPage.processPage.elementUrls["_VNpT0FY5EdqI9sTOt2pjHw"] = ["Analista","openup/capabilitypatterns/analyst_6A1AA080.html"];
contentPage.processPage.elementUrls["_QN4E4ALlEduHjPEP_YPH-g"] = ["Caso de Uso","openup/capabilitypatterns/use_case_CED07C69.html"];
contentPage.processPage.elementUrls["_5v0NwBOKEduCNqgZdt_OaA"] = ["Marco da Liberação do Produto","openup/deliveryprocesses/product_release_E215D8A8.html"];
contentPage.processPage.elementUrls["_0uyGoMlgEdmt3adZL5Dmdw"] = ["Ciclo de Vida do OpenUP","openup/deliveryprocesses/openup_lifecycle_2CB8A7DA.html"];
contentPage.processPage.elementUrls["_wGeiAFY6EdqI9sTOt2pjHw"] = ["Caso de Uso","openup/capabilitypatterns/use_case_BBBA3588.html"];
contentPage.processPage.elementUrls["_TPsdoEmSEduO0bs89Khm8Q"] = ["Avaliar os Resultados","openup/capabilitypatterns/assess_results_DB6B9448.html"];
contentPage.processPage.elementUrls["_0rilYclgEdmt3adZL5Dmdw"] = ["Testar a Solução","openup/capabilitypatterns/Test Solution_508027B8.html"];
contentPage.processPage.elementUrls["_4x060FY1EdqI9sTOt2pjHw"] = ["Qualquer Papel","openup/capabilitypatterns/any_role_3395692A.html"];
contentPage.processPage.elementUrls["_XKbwoFY5EdqI9sTOt2pjHw"] = ["Plano de Projeto","openup/capabilitypatterns/project_plan_24B37F0D.html"];
contentPage.processPage.elementUrls["_5LsMUFY1EdqI9sTOt2pjHw"] = ["Solicitar Mudança","openup/capabilitypatterns/request_change_1290834C.html"];
contentPage.processPage.elementUrls["_a7FlQkr_EeKX7P2uP3m2zg"] = ["Levantar Requisitos","openup/deliveryprocesses/Levantar Requisitos_42A01D00.html"];
contentPage.processPage.elementUrls["_qQppAFY4EdqI9sTOt2pjHw"] = ["Caderno de Arquitetura","openup/capabilitypatterns/architecture_notebook_F2777AB2.html"];
contentPage.processPage.elementUrls["_mZDP4FY5EdqI9sTOt2pjHw"] = ["Gerente de Projeto","openup/capabilitypatterns/project_manager_23170FF9.html"];
contentPage.processPage.elementUrls["_hApmMEhKEeKGbNSAHWDTsQ"] = ["Executar os Testes","openup/deliveryprocesses/run_tests_F2464EE3.html"];
contentPage.processPage.elementUrls["_MEf8YkhKEeKGbNSAHWDTsQ"] = ["Planejar e Gerenciar a iteração","openup/deliveryprocesses/manage_iteration_84046711.html"];
contentPage.processPage.elementUrls["_r1Xe0DeqEduCsbgJNeFsSw"] = ["Modelo de Caso de Uso","openup/capabilitypatterns/uc_model_361896B2.html"];
contentPage.processPage.elementUrls["_wGw14FY6EdqI9sTOt2pjHw"] = ["Visão","openup/capabilitypatterns/vision_C6D6A6B.html"];
contentPage.processPage.elementUrls["_bWELsd1qEduavbdP4P0fvw"] = ["Desenvolver um Incremento da Solução","openup/capabilitypatterns/develop_solution_436ECE62.html"];
contentPage.processPage.elementUrls["_R5HjkEsBEeKX7P2uP3m2zg"] = ["Plano de Projeto","openup/deliveryprocesses/project_plan_2CD8036B.html"];
contentPage.processPage.elementUrls["_0o3r4slgEdmt3adZL5Dmdw"] = ["Iteração da Fase de Concepção","openup/capabilitypatterns/inception_phase_iteration_C2188B46.html"];
contentPage.processPage.elementUrls["_0Spa4BOKEduCNqgZdt_OaA"] = ["Iteração de Elaboração [1..n]","openup/deliveryprocesses/elaboration_phase_iteration_427C4DE0.html"];
contentPage.processPage.elementUrls["_eGuMB0bpEduLBN1xMBngqw"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_6B2CF932.html"];
contentPage.processPage.elementUrls["_y-k0bOtQEdqc1LGhiSPqRg"] = ["Planejar e Gerenciar a iteração","openup/capabilitypatterns/manage_iteration_4EF10D2F.html"];
contentPage.processPage.elementUrls["_eHAf4kbpEduLBN1xMBngqw"] = ["Caso de Teste","openup/capabilitypatterns/test_case_57B5BBC9.html"];
contentPage.processPage.elementUrls["_oSQYEL3SEdqfrv3k16plXw"] = ["Registro de Teste","openup/capabilitypatterns/test_log_C5FF02E2.html"];
contentPage.processPage.elementUrls["_XKVqAFY5EdqI9sTOt2pjHw"] = ["Gerente de Projeto","openup/capabilitypatterns/project_manager_24E88681.html"];
contentPage.processPage.elementUrls["_0nz79clgEdmt3adZL5Dmdw"] = ["Testar a Solução","openup/capabilitypatterns/test_solution_59590D2E.html"];
contentPage.processPage.elementUrls["_WrXvwPinEdmugcVr9AdHjQ"] = ["Desenvolver um Incremento da Solução","openup/capabilitypatterns/develop_solution_D6782BA8.html"];
contentPage.processPage.elementUrls["_S8dNQMBFEdqSgKaj2SZBmg"] = ["Arquiteto","openup/capabilitypatterns/architect_4A0872BF.html"];
contentPage.processPage.elementUrls["_d6Q7IVY4EdqI9sTOt2pjHw"] = ["Arquitetura","openup/capabilitypatterns/architecture_212F5392.html"];
contentPage.processPage.elementUrls["_HTBBMU_dEduE1dJ2XtzzkQ"] = ["Desenvolvedor","openup/capabilitypatterns/developer_4C639004.html"];
contentPage.processPage.elementUrls["_SZOIoEmSEduO0bs89Khm8Q"] = ["Caderno de Arquitetura","openup/capabilitypatterns/architecture_notebook_8F24FBFC.html"];
contentPage.processPage.elementUrls["_kFwgIDbsEduMn613sF6-Uw"] = ["Criar os Casos de Teste","openup/capabilitypatterns/create_test_cases_9D1EBAA3.html"];
contentPage.processPage.elementUrls["_HTBBME_dEduE1dJ2XtzzkQ"] = ["Testador","openup/capabilitypatterns/tester_41C5AFF4.html"];
contentPage.processPage.elementUrls["_XTNp0khFEeKGbNSAHWDTsQ"] = ["Implementar a Arquitetura","openup/deliveryprocesses/develop_architecture_122CCD89.html"];
contentPage.processPage.elementUrls["_-YrHMFY4EdqI9sTOt2pjHw"] = ["Implementação","openup/capabilitypatterns/implementation_7F349488.html"];
contentPage.processPage.elementUrls["_eGoFY0bpEduLBN1xMBngqw"] = ["Lista de Itens de Trabalho","openup/capabilitypatterns/work_items_list_6D4977A.html"];
contentPage.processPage.elementUrls["_0o9ygclgEdmt3adZL5Dmdw"] = ["Identificar e Refinar os Requisitos","openup/capabilitypatterns/identify_and_refine_requirements_EDFE69E4.html"];
contentPage.processPage.elementUrls["_Xrrj0ASqEdy6Meh4O3uDnA"] = ["Desenvolvedor","openup/capabilitypatterns/developer_600F7DE6.html"];
contentPage.processPage.elementUrls["__BTFAClZEdytYo99TZh2Ng"] = ["Arquiteto","openup/capabilitypatterns/architect_91F909FD.html"];
contentPage.processPage.elementUrls["_y1uwgBOKEduCNqgZdt_OaA"] = ["Marcos dos Objetivos no Ciclo de Vida","openup/deliveryprocesses/lifecycle_objectives_4E2B8CB3.html"];
contentPage.processPage.elementUrls["_flCL8AirEdySCYtHvCR6bg"] = ["Registro de Teste","openup/capabilitypatterns/test_log_53CD6379.html"];
contentPage.processPage.elementUrls["_UGqaYEiqEeKstezpPgZg6Q"] = ["Release 1","openup/deliveryprocesses/New Milestone_A3528EE3.html"];
contentPage.processPage.elementUrls["_Y5DAMb-EEdqb7N6KIeDL8Q"] = ["Especificação de Requisitos Suplementares","openup/capabilitypatterns/supporting_requirements_spec_8C4155BE.html"];
contentPage.processPage.elementUrls["_ukbHgL-EEdqb7N6KIeDL8Q"] = ["Descrever a Arquitetura","openup/capabilitypatterns/outline_the_architecture_B7FD36D1.html"];
contentPage.processPage.elementUrls["_a8fNUFY2EdqI9sTOt2pjHw"] = ["Caso de Teste","openup/capabilitypatterns/test_case_99E751BB.html"];
contentPage.processPage.elementUrls["_g2XAwheDEduXJrZWmtC8tg"] = ["Glossário","openup/capabilitypatterns/glossary_9A03A599.html"];
contentPage.processPage.elementUrls["_HTpzcDSLEdursMWmT1aZyw"] = ["Modelo de Caso de Uso","openup/capabilitypatterns/uc_model_B482FAAF.html"];
contentPage.processPage.elementUrls["_0rQRgMlgEdmt3adZL5Dmdw"] = ["Iteração da Fase de Transição","openup/capabilitypatterns/transition_phase_iteration_87676AD2.html"];
contentPage.processPage.elementUrls["_DT8oAzk-EduFTqg5hiiQIw"] = ["Desenvolvedor","openup/capabilitypatterns/developer_39E4733.html"];
contentPage.processPage.elementUrls["__iDO0EhREeKGbNSAHWDTsQ"] = ["Transição","openup/deliveryprocesses/transicao_762A18C6.html"];
contentPage.processPage.elementUrls["_5M7icFY1EdqI9sTOt2pjHw"] = ["Lista de Itens de Trabalho","openup/capabilitypatterns/work_items_list_13D84957.html"];
contentPage.processPage.elementUrls["_0rcewclgEdmt3adZL5Dmdw"] = ["Desenvolver a Arquitetura","openup/capabilitypatterns/develop_architecture_4C24F4D9.html"];
contentPage.processPage.elementUrls["_-2bnsEr-EeKX7P2uP3m2zg"] = ["Definir Objetivos","openup/deliveryprocesses/Definir Objetivos_36CFF25B.html"];
contentPage.processPage.elementUrls["_xlEGoUg9EeKGbNSAHWDTsQ"] = ["Iteração 1","openup/deliveryprocesses/interacao_1_FBD842A0.html"];
contentPage.processPage.elementUrls["_R0noQEhHEeKGbNSAHWDTsQ"] = ["Arquitetura ","openup/deliveryprocesses/Arquitetura_5D665825.html"];
contentPage.processPage.elementUrls["_6QwpgA1SEdyKD8XBf_Hbrw"] = ["Integrar e Criar a Construção","openup/capabilitypatterns/integrate_and_create_build_19404C36.html"];
contentPage.processPage.elementUrls["_ezOKIE9DEdudU75l2xOQTw"] = ["Analista","openup/capabilitypatterns/analyst_1A74AEE9.html"];
contentPage.processPage.elementUrls["_eGoFZEbpEduLBN1xMBngqw"] = ["Especificação de Requisitos Suplementares","openup/capabilitypatterns/supporting_requirements_spec_6955AFAE.html"];
contentPage.processPage.elementUrls["_F6WiEMEQEduTGJ8i4u8TMw"] = ["Arquiteto","openup/capabilitypatterns/architect_5794F10E.html"];
contentPage.processPage.elementUrls["_RfwvEDOvEduqsLmIADMQ9g"] = ["Script de Teste","openup/capabilitypatterns/test_script_5A47231D.html"];
contentPage.processPage.elementUrls["_4Y1wML3JEdqfrv3k16plXw"] = ["Lista de Itens de Trabalho","openup/capabilitypatterns/work_items_list_3257BEB0.html"];
contentPage.processPage.elementUrls["_mZt-QFY5EdqI9sTOt2pjHw"] = ["Plano de Projeto","openup/capabilitypatterns/project_plan_B7AA81E9.html"];
contentPage.processPage.elementUrls["_9kUSEFY4EdqI9sTOt2pjHw"] = ["Desenvolvedor","openup/capabilitypatterns/developer_24A8709E.html"];
contentPage.processPage.elementUrls["_qQROgFY4EdqI9sTOt2pjHw"] = ["Arquiteto","openup/capabilitypatterns/architect_78315249.html"];
contentPage.processPage.elementUrls["_0oSdE8lgEdmt3adZL5Dmdw"] = ["Iniciar o Projeto","openup/capabilitypatterns/initiate_project_ED8BD86C.html"];
contentPage.processPage.elementUrls["_AdllQFY5EdqI9sTOt2pjHw"] = ["Construção","openup/capabilitypatterns/build_76876126.html"];
contentPage.processPage.elementUrls["_eHAf4EbpEduLBN1xMBngqw"] = ["Criar os Casos de Teste","openup/capabilitypatterns/create_test_case_5E7EC7A3.html"];
contentPage.processPage.elementUrls["_eFeO0kbpEduLBN1xMBngqw"] = ["Visão","openup/capabilitypatterns/vision_44AFA550.html"];
contentPage.processPage.elementUrls["_g6RngEhBEeKGbNSAHWDTsQ"] = ["Definir ferramentas","openup/deliveryprocesses/Definir ferramentas_57FB8535.html"];
contentPage.processPage.elementUrls["_oNJDsFY5EdqI9sTOt2pjHw"] = ["Gerenciar a Iteração","openup/capabilitypatterns/manage_iteration_C2AC19FA.html"];
contentPage.processPage.elementUrls["_0oreoclgEdmt3adZL5Dmdw"] = ["Obter Acordo Sobre a Abordagem Técnica","openup/capabilitypatterns/agree_technical_approach_944692EF.html"];
contentPage.processPage.elementUrls["_xupMvxOKEduCNqgZdt_OaA"] = ["Iteração de Concepção [1..n]","openup/deliveryprocesses/inception_phase_iteration_648AE2DA.html"];
contentPage.processPage.elementUrls["_wGSUwFY6EdqI9sTOt2pjHw"] = ["Analista","openup/capabilitypatterns/analyst_D7CF3250.html"];
